name = "gtz"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.

description = "A timezone data provider for Gleam! "
licences = ["Apache-2.0"]
repository = { type = "github", user = "jrstrunk", repo = "gtz" }
links = [{ title = "Website", href = "https://gleam.run" }]

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
tz = ">= 0.28.1 and < 1.0.0"
timex = ">= 3.7.11 and < 4.0.0"
gtempo = ">= 7.0.0 and < 8.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
